const Profile = require('../models/Profile');
const LearningPath = require('../models/LearningPath');
const Progress = require('../models/Progress');
const { skillGapAnalysisPrompt, generateLearningPathPrompt, careerRecommendationEnginePrompt } = require('../utils/openai');
const pdfParse = require('pdf-parse');
const { GoogleGenerativeAI } = require("@google/generative-ai");
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

exports.analyzeProfile = async (req, res) => {
  try {
    const { targetRole, skills: bodySkills, timeCommitment } = req.body;
    let profile = await Profile.findOne({ userId: req.user.id });

    // Prefer skills passed from frontend (they have user-adjusted levels)
    // Fall back to profile DB data if not provided
    let skillsWithLevels;
    if (bodySkills && bodySkills.length > 0) {
      skillsWithLevels = bodySkills.map(s => typeof s === 'string' ? { name: s, level: 50 } : s);
    } else if (profile?.skills) {
      skillsWithLevels = profile.skills;
    } else {
      skillsWithLevels = [{ name: 'JavaScript', level: 50 }];
    }

    const skillNames = skillsWithLevels.map(s => s.name);
    console.log(`Starting gap analysis for role: ${targetRole} with ${skillsWithLevels.length} skills`);
    const gapAnalysis = await skillGapAnalysisPrompt(skillNames, targetRole);

    res.json({ targetRole, skills: skillsWithLevels, timeCommitment, gapAnalysis });
  } catch (err) {
    console.error('Gap Analysis Error:', err);
    res.status(500).json({ message: 'Error analyzing profile', error: err.message });
  }
};

exports.generatePath = async (req, res) => {
  try {
    const { targetRole, gapAnalysis, skills, timeCommitment } = req.body;
    const { missingSkills, currentLevel } = gapAnalysis;

    // Build rich context for personalized generation
    const skillsWithLevels = skills || [];
    const time = timeCommitment || '5-10 hours per week';

    console.log(`Generating PERSONALIZED path for ${targetRole} | Level: ${currentLevel} | Time: ${time}`);
    const roadmapData = await generateLearningPathPrompt(
      targetRole, currentLevel, missingSkills, skillsWithLevels, time
    );

    if (!roadmapData || !roadmapData.phases) {
      throw new Error('Invalid roadmap structure generated by AI');
    }

    const newPath = new LearningPath({
      userId: req.user.id,
      goal: targetRole,
      currentLevel: currentLevel,
      phases: roadmapData.phases
    });

    await newPath.save();

    const newProgress = new Progress({
      userId: req.user.id,
      learningPathId: newPath._id,
      completedTopics: [],
      progressPercentage: 0
    });

    await newProgress.save();

    res.json({ learningPath: newPath, progress: newProgress });
  } catch (err) {
    console.error("Path Generation Error:", err);
    res.status(500).json({ message: 'Error generating learning path', error: err.message });
  }
};

exports.getLearningPath = async (req, res) => {
  try {
    const { id } = req.query;

    let query = { userId: req.user.id };
    if (id) {
      query._id = id;
    }

    // Sort by newest first and get the latest
    const paths = await LearningPath.find(query).sort({ createdAt: -1 });

    if (!paths || paths.length === 0) {
      return res.status(404).json({ message: 'No learning path found' });
    }

    res.json(id ? paths[0] : paths[0]);
  } catch (err) {
    console.error("Fetch Path Error:", err);
    res.status(500).json({ message: 'Server error' });
  }
};

exports.getHistory = async (req, res) => {
  try {
    const history = await LearningPath.find({ userId: req.user.id }).sort({ createdAt: -1 });
    res.json(history);
  } catch (err) {
    res.status(500).json({ message: 'Server error' });
  }
};

exports.deleteLearningPath = async (req, res) => {
  try {
    const { id } = req.params;

    // Ensure the path belongs to the user
    const path = await LearningPath.findOne({ _id: id, userId: req.user.id });
    if (!path) {
      return res.status(404).json({ message: 'Learning path not found or unauthorized' });
    }

    await LearningPath.findByIdAndDelete(id);

    // Also clean up associated progress
    await Progress.deleteMany({ learningPathId: id });

    res.json({ message: 'Learning path deleted successfully' });
  } catch (err) {
    console.error("Delete Path Error:", err);
    res.status(500).json({ message: 'Error deleting learning path', error: err.message });
  }
};

exports.chat = async (req, res) => {
  try {
    const { message } = req.body;
    const profile = await Profile.findOne({ userId: req.user.id });
    const paths = await LearningPath.find({ userId: req.user.id }).sort({ createdAt: -1 });
    const learningPath = paths[0] || { goal: 'Professional Growth' };

    // System Context for Hercai
    const context = `You are a senior career mentor. User Goal: ${learningPath.goal}. `;
    const fullPrompt = context + "User asks: " + message;

    // Fetch Real-time AI response with Gemini
    let finalReply;
    let success = false;

    try {
      const result = await model.generateContent(fullPrompt);
      const response = await result.response;
      const text = response.text();
      if (text) {
        finalReply = text;
        success = true;
      }
    } catch (apiErr) {
      console.error("Gemini Error:", apiErr.message);
    }

    if (!success) {
      finalReply = `I'm currently undergoing some high-intensity training (API busy). Stay focused on your goal: ${learningPath.goal}!`;
    }

    res.json({ response: finalReply });
  } catch (err) {
    console.error("Hercai Error:", err.message);
    res.status(500).json({ message: 'AI Connection Error: ' + err.message });
  }
};

exports.recommendCareerEngine = async (req, res) => {
  try {
    let inputText = '';

    if (req.file) {
      // Handle PDF upload
      const data = await pdfParse(req.file.buffer);
      inputText = data.text;
    } else if (req.body && req.body.text) {
      // Handle raw text input
      inputText = req.body.text;
    }

    if (!inputText || inputText.trim().length < 20) {
      return res.status(400).json({
        message: 'Not enough data to give accurate recommendation. Please provide more text.'
      });
    }

    console.log(`Analyzing career profile text (length: ${inputText.length})...`);
    const recommendationResult = await careerRecommendationEnginePrompt(inputText);

    if (typeof recommendationResult === 'string' && recommendationResult.includes("Not enough data")) {
      return res.status(400).json({ message: recommendationResult });
    }

    res.json(recommendationResult);
  } catch (err) {
    console.error("Career Engine Recommendation Error:", err);
    res.status(500).json({ message: 'Error generating career recommendation', error: err.message });
  }
};
